using System.Text;
using KicsitLibrary.Reports.Contracts;
using KicsitLibrary.Reports.Models;

namespace KicsitLibrary.Reports.Export;

public sealed class PdfReportExporter : IReportExporter
{
    private const int BodyLinesPerPage = 38;
    private const int MaximumTableWidth = 142;

    public ReportFormat Format => ReportFormat.PDF;

    public async Task<ReportExportResult> ExportAsync(
        ReportResult report,
        ReportExportRequest request,
        CancellationToken cancellationToken = default)
    {
        try
        {
            var filePath = ReportFilePathResolver.Resolve(report, request, "pdf");
            var pages = BuildPages(report);
            var bytes = BuildPdf(pages, cancellationToken);
            await File.WriteAllBytesAsync(filePath, bytes, cancellationToken);
            return new ReportExportResult
            {
                Succeeded = true,
                FilePath = filePath,
                Format = ReportFormat.PDF,
                Message = $"PDF report exported to {filePath}.",
                ExportedAt = DateTime.UtcNow
            };
        }
        catch (Exception ex)
        {
            return new ReportExportResult
            {
                Succeeded = false,
                Format = ReportFormat.PDF,
                Message = "PDF export failed.",
                ErrorMessage = ex.Message,
                ExportedAt = DateTime.UtcNow
            };
        }
    }

    private static List<List<string>> BuildPages(ReportResult report)
    {
        var tableHeader = BuildTableLine(
            report.Columns.Select(column => column.Header).ToList(),
            report.Columns.Count);
        var separator = new string('-', Math.Min(MaximumTableWidth, tableHeader.Length));
        var body = new List<string>();

        if (report.Rows.Count == 0)
        {
            body.Add("No records matched the selected filters.");
        }
        else
        {
            body.AddRange(report.Rows.Select(row => BuildTableLine(
                report.Columns.Select(column =>
                    CsvReportExporter.FormatValue(row[column.Key], column.Format)).ToList(),
                report.Columns.Count)));
        }

        if (report.SummaryItems.Count > 0)
        {
            body.Add(string.Empty);
            body.Add("SUMMARY");
            body.AddRange(report.SummaryItems.Select(item => $"{item.Key}: {item.Value}"));
        }

        var chunks = body
            .Select((line, index) => new { Line = line, Index = index })
            .GroupBy(item => item.Index / BodyLinesPerPage)
            .Select(group => group.Select(item => item.Line).ToList())
            .ToList();
        if (chunks.Count == 0)
        {
            chunks.Add(["No records matched the selected filters."]);
        }

        var pages = new List<List<string>>();
        for (var index = 0; index < chunks.Count; index++)
        {
            var page = new List<string>
            {
                report.InstitutionName.ToUpperInvariant(),
                report.ReportTitle.ToUpperInvariant(),
                $"Generated: {report.GeneratedAt:dd-MMM-yyyy HH:mm:ss}    Generated by: {report.GeneratedBy}"
            };
            page.Add(report.AppliedFilters.Count == 0
                ? "Applied filters: None"
                : $"Applied filters: {string.Join("; ", report.AppliedFilters)}");
            page.Add(string.Empty);
            page.Add(tableHeader);
            page.Add(separator);
            page.AddRange(chunks[index]);
            page.Add(string.Empty);
            page.Add($"Page {index + 1} of {chunks.Count}");
            pages.Add(page);
        }

        return pages;
    }

    private static string BuildTableLine(IReadOnlyList<string> values, int columnCount)
    {
        if (columnCount == 0)
        {
            return string.Empty;
        }

        var columnWidth = Math.Max(6, (MaximumTableWidth - ((columnCount - 1) * 3)) / columnCount);
        return string.Join(" | ", values.Select(value =>
        {
            var normalized = NormalizeText(value);
            return normalized.Length <= columnWidth
                ? normalized.PadRight(columnWidth)
                : $"{normalized[..Math.Max(1, columnWidth - 1)]}~";
        }));
    }

    private static string NormalizeText(string value)
    {
        return value
            .Replace("\r", " ", StringComparison.Ordinal)
            .Replace("\n", " ", StringComparison.Ordinal)
            .Trim();
    }

    private static byte[] BuildPdf(
        IReadOnlyList<List<string>> pages,
        CancellationToken cancellationToken)
    {
        var objectBodies = new List<string>();
        var pageObjectNumbers = new List<int>();
        var contentObjectNumbers = new List<int>();
        var nextObjectNumber = 4;
        foreach (var _ in pages)
        {
            pageObjectNumbers.Add(nextObjectNumber++);
            contentObjectNumbers.Add(nextObjectNumber++);
        }

        objectBodies.Add("<< /Type /Catalog /Pages 2 0 R >>");
        objectBodies.Add(
            $"<< /Type /Pages /Kids [{string.Join(" ", pageObjectNumbers.Select(number => $"{number} 0 R"))}] /Count {pages.Count} >>");
        objectBodies.Add("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>");

        for (var pageIndex = 0; pageIndex < pages.Count; pageIndex++)
        {
            cancellationToken.ThrowIfCancellationRequested();
            objectBodies.Add(
                $"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 842 595] /Resources << /Font << /F1 3 0 R >> >> /Contents {contentObjectNumbers[pageIndex]} 0 R >>");

            var content = new StringBuilder();
            content.AppendLine("BT");
            content.AppendLine("/F1 7 Tf");
            content.AppendLine("24 570 Td");
            foreach (var line in pages[pageIndex])
            {
                content.Append('(').Append(EscapePdfText(line)).AppendLine(") Tj");
                content.AppendLine("0 -12 Td");
            }
            content.AppendLine("ET");
            var contentText = content.ToString();
            objectBodies.Add(
                $"<< /Length {Encoding.ASCII.GetByteCount(contentText)} >>\nstream\n{contentText}endstream");
        }

        using var stream = new MemoryStream();
        using var writer = new StreamWriter(stream, Encoding.ASCII, 1024, leaveOpen: true)
        {
            NewLine = "\n"
        };
        writer.WriteLine("%PDF-1.4");
        writer.Flush();

        var offsets = new List<long> { 0 };
        for (var index = 0; index < objectBodies.Count; index++)
        {
            offsets.Add(stream.Position);
            writer.WriteLine($"{index + 1} 0 obj");
            writer.WriteLine(objectBodies[index]);
            writer.WriteLine("endobj");
            writer.Flush();
        }

        var xrefOffset = stream.Position;
        writer.WriteLine("xref");
        writer.WriteLine($"0 {objectBodies.Count + 1}");
        writer.WriteLine("0000000000 65535 f ");
        foreach (var offset in offsets.Skip(1))
        {
            writer.WriteLine($"{offset:D10} 00000 n ");
        }
        writer.WriteLine("trailer");
        writer.WriteLine($"<< /Size {objectBodies.Count + 1} /Root 1 0 R >>");
        writer.WriteLine("startxref");
        writer.WriteLine(xrefOffset);
        writer.WriteLine("%%EOF");
        writer.Flush();
        return stream.ToArray();
    }

    private static string EscapePdfText(string value)
    {
        var ascii = new string(value.Select(character =>
            character <= 127 ? character : '?').ToArray());
        return ascii
            .Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("(", "\\(", StringComparison.Ordinal)
            .Replace(")", "\\)", StringComparison.Ordinal);
    }
}
